CALL addFighter('Mordeka');
CALL addFighter('SteelRock');
CALL addFighter('Magni');
CALL addFighter('Modi');
CALL addFighter('PhilQ');
CALL addFighter('The Oracle');
CALL addFighter('Cayden');
CALL addFighter('Barin');
CALL addFighter('Donovan');
CALL addFighter('Dustin');
CALL addFighter('Cadman');
CALL addFighter('Zoran');
CALL addFighter('Osias');
CALL addFighter('Emori');
CALL addFighter('Wanheda');
